function [display,correct,incorrect] = loop0(array_name,loop_var_name)
% Function PATH3 - QMB problem loop0
%
%   display,correct,incorrect] = loop0(array_name,loop_var_name)
%       Generates the answers for QMB problem loop0. 
%
%


line_break = char([10 32 32 32 32]);
displays = {['for ii = AA' line_break 'ii' char(10) 'end'], ...
           ['ii = AA' line_break 'ii' char(10) 'end'], ...
           ['for AA' line_break 'ii' char(10) 'end'], ...
           ['for ii == AA' line_break 'ii' char(10) 'end'], ...
           ['for ii = AA' line_break 'ii' char(10)], ...
           ['for ii' line_break 'ii' char(10) 'end'], ...
           ['for ii = AA' char(10) 'end'], ...
           ['for ii = 1:10' line_break 'ii' char(10) 'end'], ...
           ['for ii = AA {' line_break 'ii' char(10) '}'], ...
           ['for ii in AA' line_break 'ii' char(10) 'end'], ...
           ['for ii < length(AA)' line_break 'ii' char(10) 'end']};
           
% Define the multiple choices
choices = {'This code has no mistakes', ...
            'This code is missing the $for/$ keyword', ...
            'This code is missing the loop variable $ii/$', ...
            'This code defines $ii/$ incorrectly with $==/$', ...
            'This code is missing the $end/$ keyword', ...
            'This code does not set values to the loop variable $ii/$', ...
            'This code is missing a statement inside the for loop', ...
            'This does not reference the variable $AA/$', ...
            'This code uses incorrect syntax to define the loop', ...
            'This code defines $ii/$ incorrectly with $in/$', ...
            'This code uses a logical statment in the for loop definition'};

% Pick one choice to display        
ind = randi(length(displays),1);
display = ['$$' displays{ind} '/$$'];
display = strrep(display,'AA',array_name);
display = strrep(display,'ii',loop_var_name);

% Get the right answer
correct = choices{ind};
correct = strrep(correct,'AA',array_name);
correct = strrep(correct,'ii',loop_var_name);

%Pick 4 wrong answers
other_ind = randsample([1:ind-1 ind+1:length(choices)],4);
incorrect = choices(other_ind);
incorrect = strrep(incorrect,'AA',array_name);
incorrect = strrep(incorrect,'ii',loop_var_name);

