function [correct,incorrect,solution] = retrieval1(chance_none)
% RETRIEVAL1 - QMB problem retrieval1
%
%   [correct,incorrect,solution] = retrieval1(chance_none)
%

%List of answers
answers = {'Name(Position)', 'Position(Name)', ...
           'Name[Position]', 'Position[Name]', ...
           '(Position)Name', '(Name)Position', ...
           '[Position]Name', '[Name]Position', ...
           'Name{Position}', 'Position{Name}', ...
           '{Position}Name', '{Name}Position', ...
           'Name = Position', 'Position = Name', ...
           'Name.Position', 'Position.Name', ...
           'Name|Position|', 'Position|Name|', ...
           '|Name|Position', '|Position|Name', ...
           'Name<Position>','Position<Name>', ...
           '<Name>Position','<Position>Name', ...
           'Name-Position','Position-Name', ...
           'Name_Position','Position_Name', ...
           'Name + Position','Position + Name', ...
           'Name+Position','Position+Name+'};

%Add the $ cause I'm lazy
for ii = 1:length(answers)
    answers{ii} = ['$' answers{ii} '/$'];
end

% Pick answers       
if rand>chance_none
    correct = answers{1};
    incorrect(1:4) = randsample(answers(2:end),4);
    incorrect(5) = {'None of these'};
    
    solution = '<p>The correct way to index arrays in Matlab is with parentheses, specifically $Name(Position)/$.</p><br/><p>Other programming languages can use different syntax. You just need to learn the specific way for your programming language of choice</p>';
    
else
    correct = 'None of these';
    incorrect = randsample(answers(2:end),5);
    
    solution = '<p>The correct way to index arrays in Matlab is with parentheses, specifically $Name(Position)/$. This is not one of the given choices, so the correct answer is "None of these".</p><br/><p>Other programming languages can use different syntax. You just need to learn the specific way for your programming language of choice</p>';
end