function [correct,incorrect,solution] = variable4(name,val,chance_none)
% VARIABLE4 - Function for QMB problem variable4
%
%  [correct,incorrect,solution] = variable4(name,val,chance_none)  
%

answers = {sprintf('%s = %d',name,val), ...
           sprintf('%d =: %s',val,name), ...        
           sprintf('%s(%d)',name,val), ...
           sprintf('%s[%d]',name,val), ...
           sprintf('%s{%d}',name,val), ...
           sprintf('%s.value = %d',name,val), ...
           sprintf('%s - %d',name,val), ...
           sprintf('%s <- %d',name,val), ...
           sprintf('%d -> %s',val,name), ...
           sprintf('int %s = %d',name,val), ...
           sprintf('%s := %d',name,val), ...
           sprintf('%s << %d',name,val), ...
           sprintf('LET %s = %d',name,val), ...
           sprintf('set %s to %d',name,val), ...
           sprintf('%s : %d',name,val), ...
           sprintf('var %s %d',name,val), ...
           sprintf('assign(''%s'',%d)',name,val), ...
           };           

%Add the $ cause I'm lazy
for ii = 1:length(answers)
    answers{ii} = ['$' answers{ii} '/$'];
end

% Pick answers       
if rand>chance_none
    correct = answers{1};
    incorrect(1:4) = randsample(answers(2:end),4);
    incorrect(5) = {'None of these'};
    
    solution = ['<p>The correct way to assign variables in Matlab is with an equal sign, e.g. $name = value/$. Therefore the correct answer is ' answers{1} '.</p><br/><p>Other programming languages can use different syntax, so you need to learn the syntax for whichever language you use.</p>'];
    
else
    correct = 'None of these';
    incorrect = randsample(answers(2:end),5);
    
    solution = ['<p>The correct way to assign variables in Matlab is with an equal sign, e.g. $name = value/$. The correct answer should be ' answers{1} ', but this is not one of your choices. Therefore, the correct answer is "None of these".</p><br/><p>Other programming languages can use different syntax, so you need to learn the syntax for whichever language you use.</p>'];
end